### ISSUE TITLE
how do you create phenotype class file and signature matrice for cibersort?

### ISSUE THREAD

**Issue by klai001** [ksosina/Strategies-for-cellular-deconvolution-in-human-brain-RNA-sequencing-data#1]
Hi Kayode,
ive read your article on F10000 research, its been helpful in helping me figuring out how to deconvolute my own brain rnaseq dataset
ive been wanting to attempt cibersort but i dont understand the guidelines on creating phenotype class file and signature matrix?
I have already a reference sample of genes X unique cell types (i.e. no replicates of celltypes) and im uncertain on how to progress from that to signature matrix after combing the internet.
the phenotype class file seems to be a pairwise comparison between two cell types? is my interpretation right? such that its only 0 (not compared),1(member 1),2 (member 2).
would very much appreciate some suggestions or advice,
and could you kindly point to me which of the scripts in this repo correspond to making those inputs?
thank you very much

**Comment by ksosina** [comment]
Hi Klai0001,

Apologies for the delay. I see that you closed this issue. Is this no longer a problem?
